# Generated by Django 5.0.6 on 2024-05-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
